# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: container.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ontainer.proto\x12\x10\x63ontainerService\"\x1a\n\x18\x43ontainerCreationRequest\"0\n\x18\x43ontainerDeletionRequest\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\"A\n\x19\x43ontainerCreationResponse\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08\"A\n\x19\x43ontainerDeletionResponse\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08\x32\xef\x01\n\x10\x43ontainerService\x12m\n\x0f\x43reateContainer\x12+.containerService.ContainerCreationResponse\x1a+.containerService.ContainerCreationResponse\"\x00\x12l\n\x0f\x44\x65leteContainer\x12*.containerService.ContainerDeletionRequest\x1a+.containerService.ContainerDeletionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'container_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CONTAINERCREATIONREQUEST']._serialized_start=37
  _globals['_CONTAINERCREATIONREQUEST']._serialized_end=63
  _globals['_CONTAINERDELETIONREQUEST']._serialized_start=65
  _globals['_CONTAINERDELETIONREQUEST']._serialized_end=113
  _globals['_CONTAINERCREATIONRESPONSE']._serialized_start=115
  _globals['_CONTAINERCREATIONRESPONSE']._serialized_end=180
  _globals['_CONTAINERDELETIONRESPONSE']._serialized_start=182
  _globals['_CONTAINERDELETIONRESPONSE']._serialized_end=247
  _globals['_CONTAINERSERVICE']._serialized_start=250
  _globals['_CONTAINERSERVICE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
